### ISSUE TITLE
Comment formatting

### ISSUE THREAD

**Issue by peareye** [wolfmoritz/blog#15]
When a comment has 2+ paragraph's it results in a solid block of text when approved and displayed on website. The email arrives with the paragraphs intact.

**Comment by wolfmoritz** [comment]
Fixed by adding the nl2br filter in _postComments.html template.
4b78625

**Comment by peareye** [comment]
I pulled from GIT have this update and it still isn't fixed. example screen capture below.

![screen shot 2016-06-01 at 11 48 54 am](https://cloud.githubusercontent.com/assets/11490640/15721713/0bd0ba92-27ef-11e6-8c50-cc5a7d401f15.png)

**Comment by wolfmoritz** [comment]
Did you copy the changed _postComments.html file to your custom theme? The line with

{{ comment.comment|nl2br }}

was changed. 

Wolf

**Comment by peareye** [comment]
That was it..oops my bad :)
