### ISSUE TITLE
Comment Submission

### ISSUE THREAD

**Issue by peareye** [wolfmoritz/blog#16]
When you submit a comment the 
"Please Leave me a Comment" text should be replaced by the 
"Thank you
Once your comment has been reviewed, it will appear." text. Now both texts remain.

![screen shot 2016-06-01 at 10 54 18 am](https://cloud.githubusercontent.com/assets/11490640/15719984/3c7e8708-27e7-11e6-9b4f-89f76be3a86b.png)

**Comment by wolfmoritz** [comment]
Fixed, but with brute force. Maybe there is a better way.
1197fa9
